#!/usr/bin/env bun
/* eslint-disable */
import { readFileSync } from "node:fs";
import * as path from "node:path";
import protobuf from "protobufjs";
import { buildProtobufEsWrapper } from "./protobuf-es-wrapper-template.ts";
import { buildElectrobunViewCore } from "./electrobun-view-core-template.ts";
import { buildElectrobunBun } from "./electrobun-bun-template.ts";
import { buildElectrobunRpcSchema } from "./electrobun-rpc-schema-template.ts";

interface ProtoFile {
  name: string;
  package: string;
  messageType: any[];
  enumType: any[];
  service: Service[];
  options: any;
}

interface Service {
  name: string;
  method: Method[];
}

interface Method {
  name: string;
  input_type: string;
  output_type: string;
  client_streaming: boolean;
  server_streaming: boolean;
  options: any;
}

const contributorNotice = `// NOTE TO REACT-NATIVE-TURBO-LND CONTRIBUTORS:
// This file is automatically generated by the protoc plugin inside the
// protoc-generator folder.
// Any changes to this file should be made there instead.`;

const lowercaseFirst = (str: string): string =>
  str.charAt(0).toLowerCase() + str.slice(1);

async function loadProtoFiles() {
  const protoDir = path.resolve(process.cwd(), "protos");
  const descriptorPath = path.resolve(
    protoDir,
    "google",
    "protobuf",
    "descriptor.proto"
  );
  const pluginPath = path.resolve(protoDir, "plugin.proto");

  const root = new protobuf.Root();
  await root.load(descriptorPath, { keepCase: true });
  await root.load(pluginPath, { keepCase: true });
  return root;
}

function extractComments(filePath: string): Record<string, string> {
  const content = readFileSync(path.join("..", "proto", filePath), "utf8");
  const lines = content.split("\n");
  const comments: Record<string, string> = {};
  let currentComment: string[] = [];
  let isInComment = false;
  let currentMethod: string | null = null;

  lines.forEach((line, index) => {
    const trimmedLine = line.trim();
    if (trimmedLine.startsWith("/*")) {
      isInComment = true;
      currentComment = [];
    } else if (trimmedLine.endsWith("*/")) {
      isInComment = false;
      // Look ahead for the method name
      for (let i = index + 1; i < lines.length; i++) {
        const nextLine = lines[i].trim();
        if (nextLine.startsWith("rpc ")) {
          currentMethod = nextLine.split(" ")[1];
          break;
        }
      }
      if (currentMethod) {
        comments[currentMethod] = currentComment.join("\n");
      }
    } else if (isInComment) {
      // Remove leading "*"" if present, but keep the space after it
      const commentLine = trimmedLine.startsWith("*")
        ? " " + trimmedLine.slice(1)
        : trimmedLine;
      currentComment.push(commentLine);
    }
  });

  return comments;
}

function formatComment(comment: string, method: Method): string {
  const lines = comment.split("\n");
  let formattedLines = ["   *"]; // Start with an empty line
  let lastLineWasEmpty = true;

  lines.forEach((line) => {
    const trimmedLine = line.trim();
    if (trimmedLine === "") {
      if (!lastLineWasEmpty) {
        formattedLines.push("   *");
        lastLineWasEmpty = true;
      }
    } else {
      formattedLines.push(`   * ${trimmedLine}`);
      lastLineWasEmpty = false;
    }
  });

  // Add input and output types
  const inputType = method.input_type.split(".").pop();
  const outputType = method.output_type.split(".").pop();
  formattedLines.push("   *");
  formattedLines.push(`   * @param [${inputType}]`);
  formattedLines.push(`   * @returns [${outputType}]`);

  // Add an empty line at the end if it doesn't already exist
  if (!lastLineWasEmpty) {
    formattedLines.push("   *");
  }

  return `/**\n${formattedLines.join("\n")}\n   */`;
}

function generateCode(request: any): {
  cppContent: string;
  cppHeaderContent: string;
  turboSpec: string;
  protobufEsWrapper: string;
  protobufEsWrapperBrowser: string;
  protobufEsWrapperWeb: string;
  protobufEsWrapperMock: string;
  browserCoreManifest: string;
  protobufEsWrapperElectrobun: string;
  electrobunViewCore: string;
  electrobunBun: string;
  electrobunRpcSchema: string;
} {
  const cppHeaderResult: string[] = [];
  const cppResult: string[] = [];
  const turboSpecResult: string[] = [];
  const protobufEsWrapperResult: string[] = [];
  const electrobunUnaryMethods: string[] = [];
  const electrobunServerStreamingMethods: string[] = [];
  const electrobunBidiStreamingMethods: string[] = [];
  const browserRpcMethodEntries = new Map<string, string>();

  const comments: Record<string, string> = {};
  request.proto_file.forEach((protoFile: ProtoFile) => {
    const filePath = protoFile.name;
    Object.assign(comments, extractComments(filePath));
  });

  request.proto_file.forEach((protoFile: ProtoFile) => {
    // console.log("protoFile",protoFile);process.exit(0);
    // console.log(protoFile,"protoFile");return;
    if (protoFile.service && Array.isArray(protoFile.service)) {
      protoFile.service.forEach((service: Service) => {
        // console.log("protoFile.name",protoFile.name,"\n");
        // console.log("service.name",service.name,"\n");
        const serviceName = service.name;

        if (service.method && Array.isArray(service.method)) {
          service.method.forEach((method: Method) => {
            let methodName = method.name;
            if (
              serviceName === "Lightning" ||
              serviceName === "WalletUnlocker" ||
              serviceName === "State"
            ) {
              methodName = lowercaseFirst(methodName);
            } else {
              methodName = lowercaseFirst(serviceName + methodName);
            }

            const [_, inputTypeService, inputType] =
              method.input_type.split(".");
            const [_2, outputTypeService, outputType] =
              method.output_type.split(".");
            const isServerStreaming = method.server_streaming;
            const isClientStreaming = method.client_streaming;
            const rpcMethodName =
              serviceName === "Lightning" ||
              serviceName === "WalletUnlocker" ||
              serviceName === "State"
                ? method.name
                : serviceName + method.name;

            browserRpcMethodEntries.set(methodName, rpcMethodName);

            if (!isServerStreaming && !isClientStreaming) {
              electrobunUnaryMethods.push(methodName);
            } else if (isServerStreaming && !isClientStreaming) {
              electrobunServerStreamingMethods.push(methodName);
            } else if (isClientStreaming && isServerStreaming) {
              electrobunBidiStreamingMethods.push(methodName);
            }

            // Get comment from extracted comments
            const comment = comments[method.name]
              ? formatComment(comments[method.name]!, method)
              : formatComment("", method); // If no comment, still include input/output types

            // Generate C++ and React Native code (implementation omitted for brevity)
            let cppMethodDeclaration;
            let cppMethodImplementation;
            let rnMethodSpec;
            let protobufEsWrapperMethod;

            if (!isServerStreaming && !isClientStreaming) {
              // Unary RPC
              cppMethodDeclaration = `  facebook::react::AsyncPromise<std::string> ${methodName}(jsi::Runtime &rt, jsi::String data);`;
              cppMethodImplementation = `
facebook::react::AsyncPromise<std::string> TurboLndModule::${methodName}(jsi::Runtime &rt, jsi::String data) {
    auto promise = std::make_shared<facebook::react::AsyncPromise<std::string>>(rt, jsInvoker_);
    uint64_t promiseId = PromiseKeeper::getInstance().addPromise(promise);

    CCallback callback = {
        .onResponse = &promiseOnResponseStatic,
        .onError = &promiseOnErrorStatic,
        .responseContext = static_cast<uintptr_t>(promiseId),
        .errorContext = static_cast<uintptr_t>(promiseId)
    };

    std::string decodedData = base64::from_base64(data.utf8(rt));
    ::${methodName}(decodedData.data(), static_cast<int>(decodedData.size()), callback);

    return *promise;
}`;
              rnMethodSpec = `  ${comment}\n  ${methodName}(data: ProtobufBase64): Promise<ProtobufBase64>;`;

              protobufEsWrapperMethod = `${comment}
export async function ${methodName}(
  request: MessageInitShape<typeof ${inputTypeService}.${inputType}Schema>
): Promise<${outputTypeService}.${outputType}> {
  const message = create(
    ${inputTypeService}.${inputType}Schema,
    request
  );
  const b64 = await TurboLnd.${methodName}(
    base64Encode(
      toBinary(${inputTypeService}.${inputType}Schema, message)
    )
  );
  const response = fromBinary(
    ${outputTypeService}.${outputType}Schema,
    base64Decode(b64)
  );
  return response;
}
`;
            } else if (isServerStreaming && !isClientStreaming) {
              // Server streaming RPC
              cppMethodDeclaration = `  facebook::jsi::Function ${methodName}(jsi::Runtime &rt, jsi::String data, AsyncCallback<std::string> onResponse, AsyncCallback<std::string> onError);`;
              cppMethodImplementation = `
facebook::jsi::Function TurboLndModule::${methodName}(jsi::Runtime &rt, jsi::String data, AsyncCallback<std::string> onResponse, AsyncCallback<std::string> onError) {
    auto sharedOnResponse = std::make_shared<AsyncCallback<std::string>>(std::move(onResponse));
    auto sharedOnError = std::make_shared<AsyncCallback<std::string>>(std::move(onError));
    uint64_t callbackId = CallbackKeeper::getInstance().addCallbacks(sharedOnResponse, sharedOnError);

    CRecvStream recvStream = {
        .onResponse = &callbackOnResponseStatic,
        .onError = &callbackOnErrorStatic,
        .responseContext = static_cast<uintptr_t>(callbackId),
        .errorContext = static_cast<uintptr_t>(callbackId),
    };

    std::string decodedData = base64::from_base64(data.utf8(rt));
    ::${methodName}(decodedData.data(), static_cast<int>(decodedData.size()), recvStream);

    auto unsubscribeFunc = jsi::Function::createFromHostFunction(
        rt,
        jsi::PropNameID::forAscii(rt, "unsubscribe"),
        0,
        [callbackId](jsi::Runtime& rt, const jsi::Value& thisValue, const jsi::Value* arguments, size_t count) -> jsi::Value {
            CallbackKeeper::getInstance().removeCallbacks(callbackId);
            return jsi::Value::undefined();
        }
    );

    return unsubscribeFunc;
}`;
              rnMethodSpec = `  ${comment}\n  ${methodName}(data: ProtobufBase64, onResponse: OnResponseCallback, onError: OnErrorCallback): UnsubscribeFromStream;`;

              protobufEsWrapperMethod = `${comment}
export function ${methodName}(
  request: MessageInitShape<typeof ${inputTypeService}.${inputType}Schema>,
  onResponse: (response: ${outputTypeService}.${outputType}) => void,
  onError: (error: string) => void
): UnsubscribeFromStream {
  const message = create(
    ${inputTypeService}.${inputType}Schema,
    request
  );
  const requestB64 = base64Encode(
    toBinary(${inputTypeService}.${inputType}Schema, message)
  );

  const onResponseWrapper: OnResponseCallback = (responseB64) => {
    onResponse(fromBinary(
      ${outputTypeService}.${outputType}Schema,
      base64Decode(responseB64)
    ));
  }
  const onErrorWrapper: OnErrorCallback = (error: string) => onError(error);


  return TurboLnd.${methodName}(requestB64, onResponseWrapper, onErrorWrapper);
}
`;
            } else if (isClientStreaming && isServerStreaming) {
              // Bidirectional streaming RPC
              cppMethodDeclaration = `  jsi::Object ${methodName}(jsi::Runtime &rt, AsyncCallback<std::string> onResponse, AsyncCallback<std::string> onError);`;
              cppMethodImplementation = `
jsi::Object TurboLndModule::${methodName}(jsi::Runtime &rt, AsyncCallback<std::string> onResponse, AsyncCallback<std::string> onError) {
    auto sharedOnResponse = std::make_shared<AsyncCallback<std::string>>(std::move(onResponse));
    auto sharedOnError = std::make_shared<AsyncCallback<std::string>>(std::move(onError));
    uint64_t callbackId = CallbackKeeper::getInstance().addCallbacks(sharedOnResponse, sharedOnError);

    CRecvStream recvStream = {
        .onResponse = &callbackOnResponseStatic,
        .onError = &callbackOnErrorStatic,
        .responseContext = static_cast<uintptr_t>(callbackId),
        .errorContext = static_cast<uintptr_t>(callbackId),
    };

    uintptr_t streamPtr = ::${methodName}(recvStream);

    if (streamPtr != 0) {
        auto hostObject = std::make_shared<WritableStreamHostObject>(streamPtr, callbackId);
        return jsi::Object::createFromHostObject(rt, hostObject);
    } else {
        throw jsi::JSError(rt, "Failed to start ${methodName}");
    }
}`;
              rnMethodSpec = `  ${comment}\n  ${methodName}(onResponse: OnResponseCallback, onError: OnErrorCallback): WriteableStream;`;

              protobufEsWrapperMethod = `${comment}
export function ${methodName}(
  onResponse: (response: ${outputTypeService}.${outputType}) => void,
  onError: (error: string) => void
) {
  const onResponseWrapper: OnResponseCallback = (responseB64) => {
    onResponse(fromBinary(
      ${outputTypeService}.${outputType}Schema,
      base64Decode(responseB64)
    ));
  }
  const onErrorWrapper: OnErrorCallback = (error: string) => onError(error);

  const writeableStream = TurboLnd.${methodName}(onResponseWrapper, onErrorWrapper);

  return {
    send: (response: MessageInitShape<typeof ${inputTypeService}.${inputType}Schema>) => {
      const message = create(
        ${inputTypeService}.${inputType}Schema,
        response
      );
      const responseB64 = base64Encode(
        toBinary(${inputTypeService}.${inputType}Schema, message)
      );
      writeableStream.send(responseB64);
    },
    close: () => {
      writeableStream.stop();
    }
  }
}`;
            }

            if (cppMethodDeclaration) {
              cppHeaderResult.push(cppMethodDeclaration);
            }
            if (cppMethodImplementation) {
              cppResult.push(cppMethodImplementation);
            }
            if (rnMethodSpec) {
              turboSpecResult.push(rnMethodSpec);
            }
            if (protobufEsWrapperMethod) {
              protobufEsWrapperResult.push(protobufEsWrapperMethod);
            }
          });
        }
      });
    }
  });

  // Combine results into final content strings
  const cppHeaderContent = `${contributorNotice}
#pragma once

// Windows
#if defined(_WIN32) && __has_include("windows-jsi/ReactNativeTurboLndJSI.h")
#include "windows-jsi/ReactNativeTurboLndJSI.h"
// Apple
#elif __has_include(<React-Codegen/RNTurboLndSpecJSI.h>)
#include <React-Codegen/RNTurboLndSpecJSI.h>
// Android
#elif __has_include("RNTurboLndSpecJSI.h")
#include "RNTurboLndSpecJSI.h"
#endif

#include <memory>
#include <string>

#include <react/bridging/Promise.h>

namespace facebook::react {

class TurboLndModule : public NativeTurboLndCxxSpec<TurboLndModule> {
 public:
  explicit TurboLndModule(std::shared_ptr<CallInvoker> jsInvoker);

  static void promiseOnResponseStatic(void* context, const char* data, int length);
  static void promiseOnErrorStatic(void* context, const char* error);
  static void startOnResponseStatic(void* context, const char* data, int length);
  static void callbackOnResponseStatic(void* context, const char* data, int length);
  static void callbackOnErrorStatic(void* context, const char* error);


  facebook::react::AsyncPromise<std::string> start(jsi::Runtime &rt, jsi::String args);

${cppHeaderResult.join("\n\n")}


};

} // namespace facebook::react
`;

  const cppContent = `${contributorNotice}
#include "TurboLndModule.h"

#if defined(_WIN32)
#include "liblnd_windows/liblnd.h"
#else
#include "liblnd.h"
#endif

#include "utils/PromiseKeeper.h"
#include "utils/CallbackKeeper.h"
#include "utils/WritableStreamHostObject.h"
#include "utils/base64.hpp"
#include "utils/log.h"

namespace facebook::react {

TurboLndModule::TurboLndModule(std::shared_ptr<CallInvoker> jsInvoker)
    : NativeTurboLndCxxSpec(std::move(jsInvoker)) {}

void TurboLndModule::promiseOnResponseStatic(void* context, const char* data, int length) {
    uint64_t id = static_cast<uint64_t>(reinterpret_cast<uintptr_t>(context));

    if (length < 0 || (length > 0 && data == nullptr)) {
        PromiseKeeper::getInstance().rejectPromise(id, "invalid callback payload");
        return;
    }

    std::string encoded = length > 0
        ? base64::to_base64(std::string_view(data, static_cast<size_t>(length)))
        : std::string{};

    if (data) {
        ::lndFree(const_cast<char*>(data));
    }

    PromiseKeeper::getInstance().resolvePromise(id, std::move(encoded));
}

void TurboLndModule::promiseOnErrorStatic(void* context, const char* error) {
    uint64_t id = static_cast<uint64_t>(reinterpret_cast<uintptr_t>(context));

    std::string msg = error ? std::string(error) : "unknown error";

    if (error) {
        ::lndFree(const_cast<char*>(error));
    }

    PromiseKeeper::getInstance().rejectPromise(id, std::move(msg));
}

void TurboLndModule::startOnResponseStatic(void* context, const char* data, int length) {
    uint64_t id = static_cast<uint64_t>(reinterpret_cast<uintptr_t>(context));

    if (length < 0 || (length > 0 && data == nullptr)) {
        PromiseKeeper::getInstance().rejectPromise(id, "invalid callback payload");
        return;
    }

    if (data) {
        ::lndFree(const_cast<char*>(data));
    }

    PromiseKeeper::getInstance().resolvePromise(id, "");
}

void TurboLndModule::callbackOnResponseStatic(void* context, const char* data, int length) {
    uint64_t id = static_cast<uint64_t>(reinterpret_cast<uintptr_t>(context));

    if (length < 0 || (length > 0 && data == nullptr)) {
        CallbackKeeper::getInstance().invokeErrorCallback(id, "invalid callback payload");
        return;
    }

    std::string encoded = length > 0
        ? base64::to_base64(std::string_view(data, static_cast<size_t>(length)))
        : std::string{};

    if (data) {
        ::lndFree(const_cast<char*>(data));
    }

    CallbackKeeper::getInstance().invokeResponseCallback(id, std::move(encoded));
}

void TurboLndModule::callbackOnErrorStatic(void* context, const char* error) {
    uint64_t id = static_cast<uint64_t>(reinterpret_cast<uintptr_t>(context));

    std::string msg = error ? std::string(error) : "unknown error";

    if (error) {
        ::lndFree(const_cast<char*>(error));
    }

    CallbackKeeper::getInstance().invokeErrorCallback(id, std::move(msg));
}



facebook::react::AsyncPromise<std::string> TurboLndModule::start(jsi::Runtime &rt, jsi::String args) {
    auto promise = std::make_shared<facebook::react::AsyncPromise<std::string>>(rt, jsInvoker_);
    uint64_t promiseId = PromiseKeeper::getInstance().addPromise(promise);

    CCallback callback = {
        .onResponse = &startOnResponseStatic,
        .onError = &promiseOnErrorStatic,
        .responseContext = static_cast<uintptr_t>(promiseId),
        .errorContext = static_cast<uintptr_t>(promiseId)
    };

    std::string argsStr = args.utf8(rt);
    char* mutableArgs = const_cast<char*>(argsStr.c_str());

    ::start(mutableArgs, callback);

    return *promise;
}


${cppResult.join("\n\n")}


} // namespace facebook::react
`;

  const turboSpec = `${contributorNotice}
/* eslint-disable */
import type { TurboModule } from "react-native";
import { TurboModuleRegistry } from "react-native";

// Protobufs will be encoded as base64 strings.
// Use a protobuf utility like protobufjs or protobuf-es to encode/decode them.
export type ProtobufBase64 = string;

// Bidi streams will return this interface for where can send data to the
// stream.
export interface WriteableStream {
  send: (data: ProtobufBase64) => boolean;
  stop: () => boolean;
}

// Read streams will call OnResponseCallback when data is available.
// UnsubscribeFromStream can be used to stop the stream.
export type OnResponseCallback = (data: ProtobufBase64) => void;
export type OnErrorCallback = (error: string) => void;
export type UnsubscribeFromStream = () => void;

export interface Spec extends TurboModule {
  /**
   *
   * Starts up lnd.
   * You need to provide path to the app's local dir to lnd via \`--lnddir\` arg.
   * Use \`subscribeState\` to know when lnd is ready for wallet unlock/creation.
   *
   */
  start: (args: string) => Promise<string>;

${turboSpecResult.join("\n\n")}
}

export default TurboModuleRegistry.getEnforcing<Spec>("TurboLndModuleCxx");
`;

  const uniqueUnaryMethods = Array.from(new Set(electrobunUnaryMethods));
  const uniqueServerStreamingMethods = Array.from(
    new Set(electrobunServerStreamingMethods)
  );
  const uniqueBidiStreamingMethods = Array.from(
    new Set(electrobunBidiStreamingMethods)
  );
  const methodsSource = protobufEsWrapperResult.join("\n\n");
  const protobufEsWrapper = buildProtobufEsWrapper({
    contributorNotice,
    backendModulePath: "./core/NativeTurboLnd",
    rootPrefix: ".",
    methodsSource,
  });
  const protobufEsWrapperBrowser = buildProtobufEsWrapper({
    contributorNotice,
    backendModulePath: "./core/NativeTurboLnd.web",
    rootPrefix: ".",
    methodsSource,
  });
  const protobufEsWrapperWeb = buildProtobufEsWrapper({
    contributorNotice,
    backendModulePath: "./core/NativeTurboLnd.metro-web",
    rootPrefix: ".",
    methodsSource,
  });
  const protobufEsWrapperMock = buildProtobufEsWrapper({
    contributorNotice,
    backendModulePath: "./mocks/index",
    rootPrefix: ".",
    methodsSource,
  });
  const protobufEsWrapperElectrobun = buildProtobufEsWrapper({
    contributorNotice,
    backendModulePath: "./view-core",
    rootPrefix: "..",
    methodsSource,
  });
  const electrobunViewCore = buildElectrobunViewCore({
    contributorNotice,
    unaryMethods: uniqueUnaryMethods,
    serverStreamingMethods: uniqueServerStreamingMethods,
    bidiStreamingMethods: uniqueBidiStreamingMethods,
  });
  const electrobunBun = buildElectrobunBun({
    contributorNotice,
    unaryMethods: uniqueUnaryMethods,
    serverStreamingMethods: uniqueServerStreamingMethods,
    bidiStreamingMethods: uniqueBidiStreamingMethods,
  });
  const electrobunRpcSchema = buildElectrobunRpcSchema({
    contributorNotice,
    unaryMethods: uniqueUnaryMethods,
    serverStreamingMethods: uniqueServerStreamingMethods,
    bidiStreamingMethods: uniqueBidiStreamingMethods,
  });
  const browserCoreManifest = `${contributorNotice}
/* eslint-disable */

export const unaryMethods = ${JSON.stringify(uniqueUnaryMethods, null, 2)} as const;
export const serverStreamingMethods = ${JSON.stringify(
    uniqueServerStreamingMethods,
    null,
    2
  )} as const;
export const bidiStreamingMethods = ${JSON.stringify(
    uniqueBidiStreamingMethods,
    null,
    2
  )} as const;

export const rpcMethodNames = ${JSON.stringify(
    Object.fromEntries(browserRpcMethodEntries),
    null,
    2
  )} as const;
`;

  return {
    cppContent,
    cppHeaderContent,
    turboSpec,
    protobufEsWrapper,
    protobufEsWrapperBrowser,
    protobufEsWrapperWeb,
    protobufEsWrapperMock,
    browserCoreManifest,
    protobufEsWrapperElectrobun,
    electrobunViewCore,
    electrobunBun,
    electrobunRpcSchema,
  };
}

async function main() {
  try {
    const root = await loadProtoFiles();
    const PluginRequest = root.lookupType(
      "google.protobuf.compiler.CodeGeneratorRequest"
    );
    const PluginResponse = root.lookupType(
      "google.protobuf.compiler.CodeGeneratorResponse"
    );

    const inputBuffer = await readStdin();
    const uint8Array = new Uint8Array(inputBuffer);
    const request = PluginRequest.decode(uint8Array);
    const {
      cppContent,
      cppHeaderContent,
      turboSpec,
      protobufEsWrapper,
      protobufEsWrapperBrowser,
      protobufEsWrapperWeb,
      protobufEsWrapperMock,
      browserCoreManifest,
      protobufEsWrapperElectrobun,
      electrobunViewCore,
      electrobunBun,
      electrobunRpcSchema,
    } = generateCode(request);

    const response = PluginResponse.create({
      file: [
        {
          name: "TurboLndModule.cpp",
          content: cppContent,
        },
        {
          name: "TurboLndModule.h",
          content: cppHeaderContent,
        },
        {
          name: "core/NativeTurboLnd.ts",
          content: turboSpec,
        },
        {
          name: "index.ts",
          content: protobufEsWrapper,
        },
        {
          name: "index.browser.ts",
          content: protobufEsWrapperBrowser,
        },
        {
          name: "index.web.ts",
          content: protobufEsWrapperWeb,
        },
        {
          name: "mock.ts",
          content: protobufEsWrapperMock,
        },
        {
          name: "core/NativeTurboLnd.browser-manifest.ts",
          content: browserCoreManifest,
        },
        {
          name: "electrobun/view.ts",
          content: protobufEsWrapperElectrobun,
        },
        {
          name: "electrobun/view-core.ts",
          content: electrobunViewCore,
        },
        {
          name: "electrobun/bun.ts",
          content: electrobunBun,
        },
        {
          name: "electrobun/rpc-schema.ts",
          content: electrobunRpcSchema,
        },
      ],
    });

    const responseBuffer = PluginResponse.encode(response).finish();
    // Field 2: supported_features = FEATURE_PROTO3_OPTIONAL (1)
    // We append this manually because protoc-generator/protos/plugin.proto is old
    // and doesn't include the field definition.
    const supportedFeaturesField = Uint8Array.from([0x10, 0x01]);
    const responseWithFeatures = new Uint8Array(
      responseBuffer.length + supportedFeaturesField.length
    );
    responseWithFeatures.set(responseBuffer);
    responseWithFeatures.set(supportedFeaturesField, responseBuffer.length);

    await writeStdout(responseWithFeatures);
  } catch (error) {
    if (error instanceof Error) {
      console.error("Error in plugin:", error.stack || error.message);
    } else {
      console.error("Error in plugin:", error);
    }
    process.exit(1);
  }
}

async function readStdin(): Promise<Uint8Array> {
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }

  return new Uint8Array(Buffer.concat(chunks));
}

function writeStdout(data: Uint8Array): Promise<void> {
  return new Promise((resolve, reject) => {
    process.stdout.write(Buffer.from(data), (error) => {
      if (error) {
        reject(error);
        return;
      }
      resolve();
    });
  });
}

main();
