// Note to react-native-turbo-lnd contributors:
// This file is automatically generated by the protoc plugin inside the
// protoc-generator folder.
// Any changes to this file should be made there instead.
#pragma once

// Apple
#if __has_include(<React-Codegen/RNTurboLndSpecJSI.h>)
#include <React-Codegen/RNTurboLndSpecJSI.h>
// Android
#elif __has_include("RNTurboLndSpecJSI.h")
#include "RNTurboLndSpecJSI.h"
#endif

#include <memory>
#include <string>

#include <react/bridging/Promise.h>
#include <react/bridging/Uint8Array.h>

namespace facebook::react {

class TurboLndModule : public NativeTurboLndCxxSpec<TurboLndModule> {
 public:
  explicit TurboLndModule(std::shared_ptr<CallInvoker> jsInvoker);

  static void promiseOnResponseStatic(void* context, const char* data, int length);
  static void promiseOnErrorStatic(void* context, const char* error);
  static void callbackOnResponseStatic(void* context, const char* data, int length);
  static void callbackOnErrorStatic(void* context, const char* error);


  facebook::react::AsyncPromise<std::string> start(jsi::Runtime &rt, jsi::String args);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletBalance(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> channelBalance(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> getTransactions(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> estimateFee(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> sendCoins(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> listUnspent(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function subscribeTransactions(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> sendMany(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> newAddress(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signMessage(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> verifyMessage(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> connectPeer(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> disconnectPeer(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> listPeers(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function subscribePeerEvents(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> getInfo(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> getDebugInfo(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> getRecoveryInfo(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> pendingChannels(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> listChannels(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function subscribeChannelEvents(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> closedChannels(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> openChannelSync(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function openChannel(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> batchOpenChannel(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> fundingStateStep(jsi::Runtime &rt, facebook::react::Uint8Array data);

  jsi::Object channelAcceptor(jsi::Runtime &rt, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::jsi::Function closeChannel(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> abandonChannel(jsi::Runtime &rt, facebook::react::Uint8Array data);

  jsi::Object sendPayment(jsi::Runtime &rt, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> sendPaymentSync(jsi::Runtime &rt, facebook::react::Uint8Array data);

  jsi::Object sendToRoute(jsi::Runtime &rt, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> sendToRouteSync(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> addInvoice(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> listInvoices(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> lookupInvoice(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function subscribeInvoices(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> decodePayReq(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> listPayments(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> deletePayment(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> deleteAllPayments(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> describeGraph(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> getNodeMetrics(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> getChanInfo(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> getNodeInfo(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> queryRoutes(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> getNetworkInfo(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> stopDaemon(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function subscribeChannelGraph(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> debugLevel(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> feeReport(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> updateChannelPolicy(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> forwardingHistory(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> exportChannelBackup(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> exportAllChannelBackups(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> verifyChanBackup(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> restoreChannelBackups(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function subscribeChannelBackups(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> bakeMacaroon(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> listMacaroonIDs(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> deleteMacaroonID(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> listPermissions(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> checkMacaroonPermissions(jsi::Runtime &rt, facebook::react::Uint8Array data);

  jsi::Object registerRPCMiddleware(jsi::Runtime &rt, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> sendCustomMessage(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function subscribeCustomMessages(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> listAliases(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> lookupHtlcResolution(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> genSeed(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> initWallet(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> unlockWallet(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> changePassword(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function subscribeState(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> getState(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> autopilotStatus(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> autopilotModifyStatus(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> autopilotQueryScores(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> autopilotSetScores(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function chainNotifierRegisterConfirmationsNtfn(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::jsi::Function chainNotifierRegisterSpendNtfn(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::jsi::Function chainNotifierRegisterBlockEpochNtfn(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::jsi::Function invoicesSubscribeSingleInvoice(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> invoicesCancelInvoice(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> invoicesAddHoldInvoice(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> invoicesSettleInvoice(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> invoicesLookupInvoiceV2(jsi::Runtime &rt, facebook::react::Uint8Array data);

  jsi::Object invoicesHtlcModifier(jsi::Runtime &rt, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> neutrinoKitStatus(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> neutrinoKitAddPeer(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> neutrinoKitDisconnectPeer(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> neutrinoKitIsBanned(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> neutrinoKitGetBlockHeader(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> neutrinoKitGetBlock(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> neutrinoKitGetCFilter(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> neutrinoKitGetBlockHash(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> peersUpdateNodeAnnouncement(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function routerSendPaymentV2(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::jsi::Function routerTrackPaymentV2(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::jsi::Function routerTrackPayments(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerEstimateRouteFee(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerSendToRoute(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerSendToRouteV2(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerResetMissionControl(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerQueryMissionControl(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerXImportMissionControl(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerGetMissionControlConfig(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerSetMissionControlConfig(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerQueryProbability(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerBuildRoute(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::jsi::Function routerSubscribeHtlcEvents(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::jsi::Function routerSendPayment(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::jsi::Function routerTrackPayment(jsi::Runtime &rt, facebook::react::Uint8Array data, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  jsi::Object routerHtlcInterceptor(jsi::Runtime &rt, AsyncCallback<facebook::react::Uint8Array> onResponse, AsyncCallback<std::string> onError);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerUpdateChanStatus(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerXAddLocalChanAliases(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> routerXDeleteLocalChanAliases(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerSignOutputRaw(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerComputeInputScript(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerSignMessage(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerVerifyMessage(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerDeriveSharedKey(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerMuSig2CombineKeys(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerMuSig2CreateSession(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerMuSig2RegisterNonces(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerMuSig2Sign(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerMuSig2CombineSig(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> signerMuSig2Cleanup(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> versionerGetVersion(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitListUnspent(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitLeaseOutput(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitReleaseOutput(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitListLeases(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitDeriveNextKey(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitDeriveKey(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitNextAddr(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitGetTransaction(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitListAccounts(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitRequiredReserve(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitListAddresses(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitSignMessageWithAddr(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitVerifyMessageWithAddr(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitImportAccount(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitImportPublicKey(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitImportTapscript(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitPublishTransaction(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitRemoveTransaction(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitSendOutputs(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitEstimateFee(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitPendingSweeps(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitBumpFee(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitListSweeps(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitLabelTransaction(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitFundPsbt(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitSignPsbt(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> walletKitFinalizePsbt(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> watchtowerGetInfo(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> watchtowerClientAddTower(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> watchtowerClientRemoveTower(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> watchtowerClientDeactivateTower(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> watchtowerClientTerminateSession(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> watchtowerClientListTowers(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> watchtowerClientGetTowerInfo(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> watchtowerClientStats(jsi::Runtime &rt, facebook::react::Uint8Array data);

  facebook::react::AsyncPromise<facebook::react::Uint8Array> watchtowerClientPolicy(jsi::Runtime &rt, facebook::react::Uint8Array data);


};

} // namespace facebook::react
