// NOTE TO REACT-NATIVE-TURBO-LND CONTRIBUTORS:
// This file is automatically generated by the protoc plugin inside the
// protoc-generator folder.
// Any changes to this file should be made there instead.
/* eslint-disable */
export type TurboLndElectrobunUnaryMethod =
  | "walletBalance"
  | "channelBalance"
  | "getTransactions"
  | "estimateFee"
  | "sendCoins"
  | "listUnspent"
  | "sendMany"
  | "newAddress"
  | "signMessage"
  | "verifyMessage"
  | "connectPeer"
  | "disconnectPeer"
  | "listPeers"
  | "getInfo"
  | "getDebugInfo"
  | "getRecoveryInfo"
  | "pendingChannels"
  | "listChannels"
  | "closedChannels"
  | "openChannelSync"
  | "batchOpenChannel"
  | "fundingStateStep"
  | "abandonChannel"
  | "sendPaymentSync"
  | "sendToRouteSync"
  | "addInvoice"
  | "listInvoices"
  | "lookupInvoice"
  | "decodePayReq"
  | "listPayments"
  | "deletePayment"
  | "deleteAllPayments"
  | "describeGraph"
  | "getNodeMetrics"
  | "getChanInfo"
  | "getNodeInfo"
  | "queryRoutes"
  | "getNetworkInfo"
  | "stopDaemon"
  | "debugLevel"
  | "feeReport"
  | "updateChannelPolicy"
  | "forwardingHistory"
  | "exportChannelBackup"
  | "exportAllChannelBackups"
  | "verifyChanBackup"
  | "restoreChannelBackups"
  | "bakeMacaroon"
  | "listMacaroonIDs"
  | "deleteMacaroonID"
  | "listPermissions"
  | "checkMacaroonPermissions"
  | "sendCustomMessage"
  | "listAliases"
  | "lookupHtlcResolution"
  | "genSeed"
  | "initWallet"
  | "unlockWallet"
  | "changePassword"
  | "getState"
  | "autopilotStatus"
  | "autopilotModifyStatus"
  | "autopilotQueryScores"
  | "autopilotSetScores"
  | "invoicesCancelInvoice"
  | "invoicesAddHoldInvoice"
  | "invoicesSettleInvoice"
  | "invoicesLookupInvoiceV2"
  | "neutrinoKitStatus"
  | "neutrinoKitAddPeer"
  | "neutrinoKitDisconnectPeer"
  | "neutrinoKitIsBanned"
  | "neutrinoKitGetBlockHeader"
  | "neutrinoKitGetBlock"
  | "neutrinoKitGetCFilter"
  | "neutrinoKitGetBlockHash"
  | "peersUpdateNodeAnnouncement"
  | "routerEstimateRouteFee"
  | "routerSendToRoute"
  | "routerSendToRouteV2"
  | "routerResetMissionControl"
  | "routerQueryMissionControl"
  | "routerXImportMissionControl"
  | "routerGetMissionControlConfig"
  | "routerSetMissionControlConfig"
  | "routerQueryProbability"
  | "routerBuildRoute"
  | "routerUpdateChanStatus"
  | "routerXAddLocalChanAliases"
  | "routerXDeleteLocalChanAliases"
  | "signerSignOutputRaw"
  | "signerComputeInputScript"
  | "signerSignMessage"
  | "signerVerifyMessage"
  | "signerDeriveSharedKey"
  | "signerMuSig2CombineKeys"
  | "signerMuSig2CreateSession"
  | "signerMuSig2RegisterNonces"
  | "signerMuSig2Sign"
  | "signerMuSig2CombineSig"
  | "signerMuSig2Cleanup"
  | "versionerGetVersion"
  | "walletKitListUnspent"
  | "walletKitLeaseOutput"
  | "walletKitReleaseOutput"
  | "walletKitListLeases"
  | "walletKitDeriveNextKey"
  | "walletKitDeriveKey"
  | "walletKitNextAddr"
  | "walletKitGetTransaction"
  | "walletKitListAccounts"
  | "walletKitRequiredReserve"
  | "walletKitListAddresses"
  | "walletKitSignMessageWithAddr"
  | "walletKitVerifyMessageWithAddr"
  | "walletKitImportAccount"
  | "walletKitImportPublicKey"
  | "walletKitImportTapscript"
  | "walletKitPublishTransaction"
  | "walletKitRemoveTransaction"
  | "walletKitSendOutputs"
  | "walletKitEstimateFee"
  | "walletKitPendingSweeps"
  | "walletKitBumpFee"
  | "walletKitListSweeps"
  | "walletKitLabelTransaction"
  | "walletKitFundPsbt"
  | "walletKitSignPsbt"
  | "walletKitFinalizePsbt"
  | "watchtowerGetInfo"
  | "watchtowerClientAddTower"
  | "watchtowerClientRemoveTower"
  | "watchtowerClientDeactivateTower"
  | "watchtowerClientTerminateSession"
  | "watchtowerClientListTowers"
  | "watchtowerClientGetTowerInfo"
  | "watchtowerClientStats"
  | "watchtowerClientPolicy";

export type TurboLndElectrobunServerStreamMethod =
  | "subscribeTransactions"
  | "subscribePeerEvents"
  | "subscribeChannelEvents"
  | "openChannel"
  | "closeChannel"
  | "subscribeInvoices"
  | "subscribeChannelGraph"
  | "subscribeChannelBackups"
  | "subscribeCustomMessages"
  | "subscribeState"
  | "chainNotifierRegisterConfirmationsNtfn"
  | "chainNotifierRegisterSpendNtfn"
  | "chainNotifierRegisterBlockEpochNtfn"
  | "invoicesSubscribeSingleInvoice"
  | "routerSendPaymentV2"
  | "routerTrackPaymentV2"
  | "routerTrackPayments"
  | "routerSubscribeHtlcEvents"
  | "routerSendPayment"
  | "routerTrackPayment";

export type TurboLndElectrobunBidiStreamMethod =
  | "channelAcceptor"
  | "sendPayment"
  | "sendToRoute"
  | "registerRPCMiddleware"
  | "invoicesHtlcModifier"
  | "routerHtlcInterceptor";

export type TurboLndElectrobunRpcSchema = {
  bun: {
    requests: {
      __TurboLndStart: {
        params: string;
        response: string;
      };
      __TurboLndUnary: {
        params: {
          method: TurboLndElectrobunUnaryMethod;
          data: string;
        };
        response: {
          data: string;
        };
      };
      __TurboLndOpenServerStream: {
        params: {
          method: TurboLndElectrobunServerStreamMethod;
          data: string;
        };
        response: {
          subscriptionId: string;
        };
      };
      __TurboLndCloseServerStream: {
        params: {
          subscriptionId: string;
        };
        response: {
          removed: boolean;
        };
      };
      __TurboLndOpenBidiStream: {
        params: {
          method: TurboLndElectrobunBidiStreamMethod;
        };
        response: {
          subscriptionId: string;
        };
      };
      __TurboLndSendBidiStream: {
        params: {
          subscriptionId: string;
          data: string;
        };
        response: {
          sent: boolean;
        };
      };
      __TurboLndStopBidiStream: {
        params: {
          subscriptionId: string;
        };
        response: {
          stopped: boolean;
        };
      };
    };
    messages: {};
  };
  webview: {
    requests: {};
    messages: {
      __TurboLndStreamEvent: {
        subscriptionId: string;
        type: "data" | "error" | "end";
        data?: string;
        error?: string;
      };
    };
  };
};
