"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.file_chainrpc_chainkit = exports.GetBlockResponseSchema = exports.GetBlockRequestSchema = exports.GetBlockHeaderResponseSchema = exports.GetBlockHeaderRequestSchema = exports.GetBlockHashResponseSchema = exports.GetBlockHashRequestSchema = exports.GetBestBlockResponseSchema = exports.GetBestBlockRequestSchema = exports.ChainKit = void 0;
var _codegenv = require("@bufbuild/protobuf/codegenv2");
// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file chainrpc/chainkit.proto (package chainrpc, syntax proto3)
/* eslint-disable */

/**
 * Describes the file chainrpc/chainkit.proto.
 */
const file_chainrpc_chainkit = exports.file_chainrpc_chainkit = /*@__PURE__*/
(0, _codegenv.fileDesc)("ChdjaGFpbnJwYy9jaGFpbmtpdC5wcm90bxIIY2hhaW5ycGMiJQoPR2V0QmxvY2tSZXF1ZXN0EhIKCmJsb2NrX2hhc2gYASABKAwiJQoQR2V0QmxvY2tSZXNwb25zZRIRCglyYXdfYmxvY2sYASABKAwiKwoVR2V0QmxvY2tIZWFkZXJSZXF1ZXN0EhIKCmJsb2NrX2hhc2gYASABKAwiMgoWR2V0QmxvY2tIZWFkZXJSZXNwb25zZRIYChByYXdfYmxvY2tfaGVhZGVyGAEgASgMIhUKE0dldEJlc3RCbG9ja1JlcXVlc3QiQAoUR2V0QmVzdEJsb2NrUmVzcG9uc2USEgoKYmxvY2tfaGFzaBgBIAEoDBIUCgxibG9ja19oZWlnaHQYAiABKAUiKwoTR2V0QmxvY2tIYXNoUmVxdWVzdBIUCgxibG9ja19oZWlnaHQYASABKAMiKgoUR2V0QmxvY2tIYXNoUmVzcG9uc2USEgoKYmxvY2tfaGFzaBgBIAEoDDLAAgoIQ2hhaW5LaXQSQQoIR2V0QmxvY2sSGS5jaGFpbnJwYy5HZXRCbG9ja1JlcXVlc3QaGi5jaGFpbnJwYy5HZXRCbG9ja1Jlc3BvbnNlElMKDkdldEJsb2NrSGVhZGVyEh8uY2hhaW5ycGMuR2V0QmxvY2tIZWFkZXJSZXF1ZXN0GiAuY2hhaW5ycGMuR2V0QmxvY2tIZWFkZXJSZXNwb25zZRJNCgxHZXRCZXN0QmxvY2sSHS5jaGFpbnJwYy5HZXRCZXN0QmxvY2tSZXF1ZXN0Gh4uY2hhaW5ycGMuR2V0QmVzdEJsb2NrUmVzcG9uc2USTQoMR2V0QmxvY2tIYXNoEh0uY2hhaW5ycGMuR2V0QmxvY2tIYXNoUmVxdWVzdBoeLmNoYWlucnBjLkdldEJsb2NrSGFzaFJlc3BvbnNlQjBaLmdpdGh1Yi5jb20vbGlnaHRuaW5nbmV0d29yay9sbmQvbG5ycGMvY2hhaW5ycGNiBnByb3RvMw");

/**
 * @generated from message chainrpc.GetBlockRequest
 */

/**
 * Describes the message chainrpc.GetBlockRequest.
 * Use `create(GetBlockRequestSchema)` to create a new message.
 */
const GetBlockRequestSchema = exports.GetBlockRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_chainrpc_chainkit, 0);

/**
 * TODO(ffranr): The neutrino GetBlock response includes many
 * additional helpful fields. Consider adding them here also.
 *
 * @generated from message chainrpc.GetBlockResponse
 */

/**
 * Describes the message chainrpc.GetBlockResponse.
 * Use `create(GetBlockResponseSchema)` to create a new message.
 */
const GetBlockResponseSchema = exports.GetBlockResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_chainrpc_chainkit, 1);

/**
 * @generated from message chainrpc.GetBlockHeaderRequest
 */

/**
 * Describes the message chainrpc.GetBlockHeaderRequest.
 * Use `create(GetBlockHeaderRequestSchema)` to create a new message.
 */
const GetBlockHeaderRequestSchema = exports.GetBlockHeaderRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_chainrpc_chainkit, 2);

/**
 * @generated from message chainrpc.GetBlockHeaderResponse
 */

/**
 * Describes the message chainrpc.GetBlockHeaderResponse.
 * Use `create(GetBlockHeaderResponseSchema)` to create a new message.
 */
const GetBlockHeaderResponseSchema = exports.GetBlockHeaderResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_chainrpc_chainkit, 3);

/**
 * @generated from message chainrpc.GetBestBlockRequest
 */

/**
 * Describes the message chainrpc.GetBestBlockRequest.
 * Use `create(GetBestBlockRequestSchema)` to create a new message.
 */
const GetBestBlockRequestSchema = exports.GetBestBlockRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_chainrpc_chainkit, 4);

/**
 * @generated from message chainrpc.GetBestBlockResponse
 */

/**
 * Describes the message chainrpc.GetBestBlockResponse.
 * Use `create(GetBestBlockResponseSchema)` to create a new message.
 */
const GetBestBlockResponseSchema = exports.GetBestBlockResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_chainrpc_chainkit, 5);

/**
 * @generated from message chainrpc.GetBlockHashRequest
 */

/**
 * Describes the message chainrpc.GetBlockHashRequest.
 * Use `create(GetBlockHashRequestSchema)` to create a new message.
 */
const GetBlockHashRequestSchema = exports.GetBlockHashRequestSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_chainrpc_chainkit, 6);

/**
 * @generated from message chainrpc.GetBlockHashResponse
 */

/**
 * Describes the message chainrpc.GetBlockHashResponse.
 * Use `create(GetBlockHashResponseSchema)` to create a new message.
 */
const GetBlockHashResponseSchema = exports.GetBlockHashResponseSchema = /*@__PURE__*/
(0, _codegenv.messageDesc)(file_chainrpc_chainkit, 7);

/**
 * ChainKit is a service that can be used to get information from the
 * chain backend.
 *
 * @generated from service chainrpc.ChainKit
 */
const ChainKit = exports.ChainKit = /*@__PURE__*/
(0, _codegenv.serviceDesc)(file_chainrpc_chainkit, 0);
//# sourceMappingURL=chainkit_pb.js.map