/* eslint-disable */
import React, { useRef, useState } from "react";
import {
  StyleSheet,
  View,
  Button,
  ScrollView,
  Text,
  TextInput,
  Platform,
} from "react-native";
import NativeExampleAppPaths from "./turbomodules/NativeExampleAppPaths";
import { loadWasmRuntime } from "react-native-turbo-lnd/wasm-load";

// The default protobuf-es bindings
import {
  start,
  getInfo,
  listChannels,
  subscribeState,
  channelAcceptor,
  listPeers,
  connectPeer,
} from "react-native-turbo-lnd";

// Access to the core API
//import TurboLnd from "react-native-turbo-lnd/core";

// protobufs generated by protobuf-es
import {
  GetInfoResponseSchema,
  SubscribeStateResponseSchema,
} from "react-native-turbo-lnd/protos/lightning_pb";

// protobuf-es helpers
import { toJson } from "@bufbuild/protobuf";

const COMMON_START_ARGS = [
  "--noseedbackup",
  "--nolisten",
  "--bitcoin.active",
  "--bitcoin.node=neutrino",
  "--bitcoin.regtest",
  '--feeurl="https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json"',
  "--routing.assumechanvalid",
  "--tlsdisableautofill",
  "--neutrino.connect=192.168.10.120:19444",
  '--debuglevel="info"',
].join(" ");

const WEB_EXTRA_START_ARGS = [
  "--norest",
  "--no-rest-tls",
  "--nobootstrap",
  "--no-macaroons",
  "--rpclisten=127.0.0.1:10009",
  "--restlisten=127.0.0.1:8080",
  "--tor.socks=127.0.0.1:9050",
  "--tor.control=127.0.0.1:9051",
].join(" ");

const NATIVE_EXTRA_START_ARGS = [
  "--db.bolt.auto-compact",
  "--db.bolt.auto-compact-min-age=0",
].join(" ");

export default function App() {
  const isWeb = Platform.OS === "web";
  const [nodeUri, setNodeUri] = useState("");
  const [logs, setLogs] = useState<string[]>([]);
  const [wasmStatus, setWasmStatus] = useState<
    "not-needed" | "not-loaded" | "loading" | "loaded" | "failed"
  >(isWeb ? "not-loaded" : "not-needed");
  const logScrollRef = useRef<ScrollView | null>(null);

  const appendLog = (...parts: unknown[]) => {
    const message = parts
      .map((part) =>
        typeof part === "string"
          ? part
          : (JSON.stringify(part, null, 2) ?? String(part))
      )
      .join(" ");

    console.log(...parts);
    setLogs((current) => [...current.slice(-199), message]);
  };

  const appendError = (...parts: unknown[]) => {
    const message = parts
      .map((part) =>
        part instanceof Error
          ? (part.stack ?? part.message)
          : typeof part === "string"
            ? part
            : (JSON.stringify(part, null, 2) ?? String(part))
      )
      .join(" ");

    console.error(...parts);
    setLogs((current) => [...current.slice(-199), `[error] ${message}`]);
  };

  const normalizeLndDirectory = (directory: string): string => {
    const normalized = directory.replace(/\\/g, "/");
    return normalized.endsWith("/") ? normalized : `${normalized}/`;
  };

  const getLndDirectory = (): string => {
    return normalizeLndDirectory(NativeExampleAppPaths.getLndDirectory());
  };

  const getStartArgs = () => {
    const lnddir = getLndDirectory();
    const extraArgs = isWeb ? WEB_EXTRA_START_ARGS : NATIVE_EXTRA_START_ARGS;

    return [`--lnddir="${lnddir}"`, COMMON_START_ARGS, extraArgs]
      .filter(Boolean)
      .join(" ");
  };

  return (
    <View style={styles.container}>
      <Button
        title={isWeb ? "load wasm" : "load wasm (web only)"}
        onPress={async () => {
          if (!isWeb) {
            appendLog("load wasm is only required on web");
            return;
          }

          setWasmStatus("loading");
          appendLog("loading wasm runtime");

          try {
            await loadWasmRuntime();
            setWasmStatus("loaded");
            appendLog("wasm runtime loaded");
          } catch (error) {
            setWasmStatus("failed");
            appendError("load wasm failed", error);
          }
        }}
      />
      <Button
        title="start"
        onPress={async () => {
          const lnddir = getLndDirectory();
          const startArgs = getStartArgs();

          appendLog("start lnddir", lnddir);
          appendLog("start args", startArgs);

          try {
            const result = await start(startArgs);

            appendLog("start result", result);
          } catch (error) {
            appendError("start failed", error);
          }
        }}
      />
      <Button
        title="getInfo"
        onPress={async () => {
          try {
            const result = await getInfo({});
            appendLog("getInfo", toJson(GetInfoResponseSchema, result));
          } catch (error) {
            appendError("getInfo failed", error);
          }
        }}
      />
      <Button
        title="getInfo loop"
        onPress={async () => {
          const startTime = performance.now();
          for (let i = 0; i < 100; i++) {
            await getInfo({});
          }
          const endTime = performance.now();
          const executionTime = endTime - startTime;

          appendLog("done");
          appendLog(`Execution time: ${executionTime} milliseconds`);
        }}
      />
      <Button
        title="subscribeState"
        onPress={async () => {
          subscribeState(
            {},
            (state) => {
              appendLog("state", toJson(SubscribeStateResponseSchema, state));
            },
            (err) => {
              appendError("error from subscribeState", err);
            }
          );
        }}
      />
      <Button
        title="channelAcceptor"
        onPress={async () => {
          const acceptor = channelAcceptor(
            (request) => {
              acceptor.send({
                accept: true,
                pendingChanId: request.pendingChanId,
              });
              appendLog("channelAcceptor request", request);
            },
            (error) => {
              appendError("channelAcceptor error", error);
            }
          );
          appendLog("channelAcceptor", acceptor);
        }}
      />
      <Button
        title="listChannels"
        onPress={async () => {
          try {
            const result = await listChannels({
              activeOnly: true,
            });

            appendLog("listChannels", result);
          } catch (error) {
            appendError("listChannels failed", error);
          }
        }}
      />
      <Button
        title="listPeers"
        onPress={async () => {
          try {
            const result = await listPeers({});

            appendLog("listPeers", result);
          } catch (error) {
            appendError("listPeers failed", error);
          }
        }}
      />
      <View style={{ flexDirection: "column" }}>
        <TextInput
          placeholder="pubkey@ip"
          value={nodeUri}
          onChangeText={setNodeUri}
          placeholderTextColor={"gray"}
          style={{ fontFamily: "monospace", color: "white" }}
        />
        <Button
          onPress={async () => {
            const [pubkey, host] = nodeUri.split("@");

            try {
              const result = await connectPeer({
                addr: {
                  host,
                  pubkey,
                },
              });
              appendLog("connectPeer", result);
            } catch (error) {
              appendError("connectPeer failed", error);
            }
          }}
          title="connectPeer"
        />
      </View>
      <Button title="clear logs" onPress={() => setLogs([])} />
      {Platform.OS === "web" && (
        <Text style={styles.statusText}>wasm status: {wasmStatus}</Text>
      )}
      <ScrollView
        ref={logScrollRef}
        style={styles.logContainer}
        contentContainerStyle={styles.logContent}
        onContentSizeChange={() =>
          logScrollRef.current?.scrollToEnd({ animated: true })
        }
      >
        {logs.map((entry, index) => (
          <Text key={`${index}-${entry}`} style={styles.logText}>
            {entry}
          </Text>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "gray",
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
  logContainer: {
    alignSelf: "stretch",
    flex: 1,
    maxHeight: 340,
    backgroundColor: "#111",
    borderRadius: 8,
    marginTop: 8,
  },
  logContent: {
    padding: 12,
    gap: 2,
  },
  logText: {
    color: "#fff",
    fontFamily: "monospace",
    fontSize: 10,
  },
  statusText: {
    color: "#fff",
    fontFamily: "monospace",
    marginTop: 8,
    marginBottom: 4,
  },
});
