/* eslint-disable */
import React, { useRef, useState } from "react";
import {
  StyleSheet,
  View,
  Button,
  ScrollView,
  Text,
  TextInput,
} from "react-native";
import NativeExampleAppPaths from "./turbomodules/NativeExampleAppPaths";

// The default protobuf-es bindings
import {
  start,
  getInfo,
  listChannels,
  subscribeState,
  channelAcceptor,
  listPeers,
  connectPeer,
} from "../../src/index";

// Access to the core API
//import TurboLnd from "../../src/core/NativeTurboLnd";

// protobufs generated by protobuf-es
import {
  GetInfoResponseSchema,
  SubscribeStateResponseSchema,
} from "../../src/proto/lightning_pb";

// protobuf-es helpers
import { toJson } from "@bufbuild/protobuf";

export default function App() {
  const [nodeUri, setNodeUri] = useState("");
  const [logs, setLogs] = useState<string[]>([]);
  const logScrollRef = useRef<ScrollView | null>(null);

  const appendLog = (...parts: unknown[]) => {
    const message = parts
      .map((part) =>
        typeof part === "string"
          ? part
          : (JSON.stringify(part, null, 2) ?? String(part))
      )
      .join(" ");

    console.log(...parts);
    setLogs((current) => [...current.slice(-199), message]);
  };

  const appendError = (...parts: unknown[]) => {
    const message = parts
      .map((part) =>
        part instanceof Error
          ? (part.stack ?? part.message)
          : typeof part === "string"
            ? part
            : (JSON.stringify(part, null, 2) ?? String(part))
      )
      .join(" ");

    console.error(...parts);
    setLogs((current) => [...current.slice(-199), `[error] ${message}`]);
  };

  const normalizeLndDirectory = (directory: string): string => {
    const normalized = directory.replace(/\\/g, "/");
    return normalized.endsWith("/") ? normalized : `${normalized}/`;
  };

  const getLndDirectory = (): string => {
    return normalizeLndDirectory(NativeExampleAppPaths.getLndDirectory());
  };

  return (
    <View style={styles.container}>
      <Button
        title="start"
        onPress={async () => {
          const lnddir = getLndDirectory();

          appendLog("start lnddir", lnddir);

          try {
            const result = await start(
              `--lnddir="${lnddir}"
              --noseedbackup
              --nolisten
              --bitcoin.active
              --bitcoin.regtest
              --bitcoin.node=neutrino
              --feeurl="https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json"
              --routing.assumechanvalid
              --tlsdisableautofill
              --db.bolt.auto-compact
              --db.bolt.auto-compact-min-age=0
              --neutrino.connect=192.168.10.120:19444`
            );

            appendLog("start result", result);
          } catch (error) {
            appendError("start failed", error);
          }
        }}
      />
      <Button
        title="getInfo"
        onPress={async () => {
          try {
            const result = await getInfo({});
            appendLog("getInfo", toJson(GetInfoResponseSchema, result));
          } catch (error) {
            appendError("getInfo failed", error);
          }
        }}
      />
      <Button
        title="getInfo loop"
        onPress={async () => {
          const startTime = performance.now();
          for (let i = 0; i < 100; i++) {
            await getInfo({});
          }
          const endTime = performance.now();
          const executionTime = endTime - startTime;

          appendLog("done");
          appendLog(`Execution time: ${executionTime} milliseconds`);
        }}
      />
      <Button
        title="subscribeState"
        onPress={async () => {
          subscribeState(
            {},
            (state) => {
              appendLog("state", toJson(SubscribeStateResponseSchema, state));
            },
            (err) => {
              appendError("error from subscribeState", err);
            }
          );
        }}
      />
      <Button
        title="channelAcceptor"
        onPress={async () => {
          const acceptor = channelAcceptor(
            (request) => {
              acceptor.send({
                accept: true,
                pendingChanId: request.pendingChanId,
              });
              appendLog("channelAcceptor request", request);
            },
            (error) => {
              appendError("channelAcceptor error", error);
            }
          );
          appendLog("channelAcceptor", acceptor);
        }}
      />
      <Button
        title="listChannels"
        onPress={async () => {
          try {
            const result = await listChannels({
              activeOnly: true,
            });

            appendLog("listChannels", result);
          } catch (error) {
            appendError("listChannels failed", error);
          }
        }}
      />
      <Button
        title="listPeers"
        onPress={async () => {
          try {
            const result = await listPeers({});

            appendLog("listPeers", result);
          } catch (error) {
            appendError("listPeers failed", error);
          }
        }}
      />
      <View style={{ flexDirection: "column" }}>
        <TextInput
          placeholder="pubkey@ip"
          value={nodeUri}
          onChangeText={setNodeUri}
          placeholderTextColor={"gray"}
          style={{ fontFamily: "monospace", color: "white" }}
        />
        <Button
          onPress={async () => {
            const [pubkey, host] = nodeUri.split("@");

            try {
              const result = await connectPeer({
                addr: {
                  host,
                  pubkey,
                },
              });
              appendLog("connectPeer", result);
            } catch (error) {
              appendError("connectPeer failed", error);
            }
          }}
          title="connectPeer"
        />
      </View>
      <Button title="clear logs" onPress={() => setLogs([])} />
      <ScrollView
        ref={logScrollRef}
        style={styles.logContainer}
        contentContainerStyle={styles.logContent}
        onContentSizeChange={() =>
          logScrollRef.current?.scrollToEnd({ animated: true })
        }
      >
        {logs.map((entry, index) => (
          <Text key={`${index}-${entry}`} style={styles.logText}>
            {entry}
          </Text>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "gray",
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
  logContainer: {
    alignSelf: "stretch",
    flex: 1,
    maxHeight: 340,
    backgroundColor: "#111",
    borderRadius: 8,
    marginTop: 8,
  },
  logContent: {
    padding: 12,
    gap: 2,
  },
  logText: {
    color: "#fff",
    fontFamily: "monospace",
    fontSize: 10,
  },
});
