/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/lightningnetwork/lnd/mobile */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 20 "autopilot_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 4 "cgo_utils_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

static inline void bridgeResponseFunc(ResponseFunc f, uintptr_t context, const char* data, int length) {
    if (f) f((void*)context, data, length);
}

static inline void bridgeErrorFunc(ErrorFunc f, uintptr_t context, const char* error) {
    if (f) f((void*)context, error);
}

// Callback
typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

// RecvStream
typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

// SendStream
typedef void (*SendFunc)(uintptr_t streamPtr, const char* data, int length);
typedef void (*StopFunc)(uintptr_t streamPtr);

typedef struct CSendStream {
    SendFunc send;
    StopFunc stop;
    uintptr_t streamPtr;
} CSendStream;

static inline CSendStream* allocCSendStream() {
    return (CSendStream*)malloc(sizeof(CSendStream));
}

static inline void freeCSendStream(CSendStream* stream) {
    if (stream != NULL) {
        free(stream);
    }
}

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "chainkit_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "chainnotifier_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 6 "cshared.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "invoices_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 17 "lightning_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "neutrinokit_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "peers_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "router_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "signer_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 3 "speedloader_cgo.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 17 "state_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "versioner_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 21 "walletkit_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 17 "walletunlocker_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "watchtower_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"

#line 20 "watchtowerclient_api_generated.go"

#ifndef CALLBACK_DEFS_H
#define CALLBACK_DEFS_H

#include <stdlib.h>
#include <stdint.h>

typedef void (*ResponseFunc)(void* context, const char* data, int length);
typedef void (*ErrorFunc)(void* context, const char* error);

typedef struct CCallback {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CCallback;

typedef struct CRecvStream {
    ResponseFunc onResponse;
    ErrorFunc onError;
    uintptr_t responseContext;
    uintptr_t errorContext;
} CRecvStream;

#endif // CALLBACK_DEFS_H

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void autopilotStatus(char* data, int length, CCallback callback);
extern __declspec(dllexport) void autopilotModifyStatus(char* data, int length, CCallback callback);
extern __declspec(dllexport) void autopilotQueryScores(char* data, int length, CCallback callback);
extern __declspec(dllexport) void autopilotSetScores(char* data, int length, CCallback callback);
extern __declspec(dllexport) void lndFree(void* ptr);
extern __declspec(dllexport) int SendStreamC(uintptr_t streamPtr, char* data, int length);
extern __declspec(dllexport) int StopStreamC(uintptr_t streamPtr);
extern __declspec(dllexport) void chainKitGetBlock(char* data, int length, CCallback callback);
extern __declspec(dllexport) void chainKitGetBlockHeader(char* data, int length, CCallback callback);
extern __declspec(dllexport) void chainKitGetBestBlock(char* data, int length, CCallback callback);
extern __declspec(dllexport) void chainKitGetBlockHash(char* data, int length, CCallback callback);
extern __declspec(dllexport) void chainNotifierRegisterConfirmationsNtfn(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void chainNotifierRegisterSpendNtfn(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void chainNotifierRegisterBlockEpochNtfn(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void start(char* extraArgs, CCallback callback);
extern __declspec(dllexport) GoInt32 getStatus(void);
extern __declspec(dllexport) void invoicesSubscribeSingleInvoice(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void invoicesCancelInvoice(char* data, int length, CCallback callback);
extern __declspec(dllexport) void invoicesAddHoldInvoice(char* data, int length, CCallback callback);
extern __declspec(dllexport) void invoicesSettleInvoice(char* data, int length, CCallback callback);
extern __declspec(dllexport) void invoicesLookupInvoiceV2(char* data, int length, CCallback callback);
extern __declspec(dllexport) uintptr_t invoicesHtlcModifier(CRecvStream rStream);
extern __declspec(dllexport) void walletBalance(char* data, int length, CCallback callback);
extern __declspec(dllexport) void channelBalance(char* data, int length, CCallback callback);
extern __declspec(dllexport) void getTransactions(char* data, int length, CCallback callback);
extern __declspec(dllexport) void estimateFee(char* data, int length, CCallback callback);
extern __declspec(dllexport) void sendCoins(char* data, int length, CCallback callback);
extern __declspec(dllexport) void listUnspent(char* data, int length, CCallback callback);
extern __declspec(dllexport) void subscribeTransactions(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void sendMany(char* data, int length, CCallback callback);
extern __declspec(dllexport) void newAddress(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signMessage(char* data, int length, CCallback callback);
extern __declspec(dllexport) void verifyMessage(char* data, int length, CCallback callback);
extern __declspec(dllexport) void connectPeer(char* data, int length, CCallback callback);
extern __declspec(dllexport) void disconnectPeer(char* data, int length, CCallback callback);
extern __declspec(dllexport) void listPeers(char* data, int length, CCallback callback);
extern __declspec(dllexport) void subscribePeerEvents(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void getInfo(char* data, int length, CCallback callback);
extern __declspec(dllexport) void getDebugInfo(char* data, int length, CCallback callback);
extern __declspec(dllexport) void getRecoveryInfo(char* data, int length, CCallback callback);
extern __declspec(dllexport) void pendingChannels(char* data, int length, CCallback callback);
extern __declspec(dllexport) void listChannels(char* data, int length, CCallback callback);
extern __declspec(dllexport) void subscribeChannelEvents(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void closedChannels(char* data, int length, CCallback callback);
extern __declspec(dllexport) void openChannelSync(char* data, int length, CCallback callback);
extern __declspec(dllexport) void openChannel(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void batchOpenChannel(char* data, int length, CCallback callback);
extern __declspec(dllexport) void fundingStateStep(char* data, int length, CCallback callback);
extern __declspec(dllexport) uintptr_t channelAcceptor(CRecvStream rStream);
extern __declspec(dllexport) void closeChannel(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void abandonChannel(char* data, int length, CCallback callback);
extern __declspec(dllexport) uintptr_t sendPayment(CRecvStream rStream);
extern __declspec(dllexport) void sendPaymentSync(char* data, int length, CCallback callback);
extern __declspec(dllexport) uintptr_t sendToRoute(CRecvStream rStream);
extern __declspec(dllexport) void sendToRouteSync(char* data, int length, CCallback callback);
extern __declspec(dllexport) void addInvoice(char* data, int length, CCallback callback);
extern __declspec(dllexport) void listInvoices(char* data, int length, CCallback callback);
extern __declspec(dllexport) void lookupInvoice(char* data, int length, CCallback callback);
extern __declspec(dllexport) void subscribeInvoices(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void deleteCanceledInvoice(char* data, int length, CCallback callback);
extern __declspec(dllexport) void decodePayReq(char* data, int length, CCallback callback);
extern __declspec(dllexport) void listPayments(char* data, int length, CCallback callback);
extern __declspec(dllexport) void deletePayment(char* data, int length, CCallback callback);
extern __declspec(dllexport) void deleteAllPayments(char* data, int length, CCallback callback);
extern __declspec(dllexport) void describeGraph(char* data, int length, CCallback callback);
extern __declspec(dllexport) void getNodeMetrics(char* data, int length, CCallback callback);
extern __declspec(dllexport) void getChanInfo(char* data, int length, CCallback callback);
extern __declspec(dllexport) void getNodeInfo(char* data, int length, CCallback callback);
extern __declspec(dllexport) void queryRoutes(char* data, int length, CCallback callback);
extern __declspec(dllexport) void getNetworkInfo(char* data, int length, CCallback callback);
extern __declspec(dllexport) void stopDaemon(char* data, int length, CCallback callback);
extern __declspec(dllexport) void subscribeChannelGraph(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void debugLevel(char* data, int length, CCallback callback);
extern __declspec(dllexport) void feeReport(char* data, int length, CCallback callback);
extern __declspec(dllexport) void updateChannelPolicy(char* data, int length, CCallback callback);
extern __declspec(dllexport) void forwardingHistory(char* data, int length, CCallback callback);
extern __declspec(dllexport) void exportChannelBackup(char* data, int length, CCallback callback);
extern __declspec(dllexport) void exportAllChannelBackups(char* data, int length, CCallback callback);
extern __declspec(dllexport) void verifyChanBackup(char* data, int length, CCallback callback);
extern __declspec(dllexport) void restoreChannelBackups(char* data, int length, CCallback callback);
extern __declspec(dllexport) void subscribeChannelBackups(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void bakeMacaroon(char* data, int length, CCallback callback);
extern __declspec(dllexport) void listMacaroonIDs(char* data, int length, CCallback callback);
extern __declspec(dllexport) void deleteMacaroonID(char* data, int length, CCallback callback);
extern __declspec(dllexport) void listPermissions(char* data, int length, CCallback callback);
extern __declspec(dllexport) void checkMacaroonPermissions(char* data, int length, CCallback callback);
extern __declspec(dllexport) uintptr_t registerRPCMiddleware(CRecvStream rStream);
extern __declspec(dllexport) void sendCustomMessage(char* data, int length, CCallback callback);
extern __declspec(dllexport) void subscribeCustomMessages(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void listAliases(char* data, int length, CCallback callback);
extern __declspec(dllexport) void lookupHtlcResolution(char* data, int length, CCallback callback);
extern __declspec(dllexport) void neutrinoKitStatus(char* data, int length, CCallback callback);
extern __declspec(dllexport) void neutrinoKitAddPeer(char* data, int length, CCallback callback);
extern __declspec(dllexport) void neutrinoKitDisconnectPeer(char* data, int length, CCallback callback);
extern __declspec(dllexport) void neutrinoKitIsBanned(char* data, int length, CCallback callback);
extern __declspec(dllexport) void neutrinoKitGetBlockHeader(char* data, int length, CCallback callback);
extern __declspec(dllexport) void neutrinoKitGetBlock(char* data, int length, CCallback callback);
extern __declspec(dllexport) void neutrinoKitGetCFilter(char* data, int length, CCallback callback);
extern __declspec(dllexport) void neutrinoKitGetBlockHash(char* data, int length, CCallback callback);
extern __declspec(dllexport) void peersUpdateNodeAnnouncement(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerSendPaymentV2(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void routerTrackPaymentV2(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void routerTrackPayments(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void routerEstimateRouteFee(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerSendToRoute(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerSendToRouteV2(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerResetMissionControl(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerQueryMissionControl(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerXImportMissionControl(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerGetMissionControlConfig(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerSetMissionControlConfig(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerQueryProbability(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerBuildRoute(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerSubscribeHtlcEvents(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void routerSendPayment(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void routerTrackPayment(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) uintptr_t routerHtlcInterceptor(CRecvStream rStream);
extern __declspec(dllexport) void routerUpdateChanStatus(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerXAddLocalChanAliases(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerXDeleteLocalChanAliases(char* data, int length, CCallback callback);
extern __declspec(dllexport) void routerXFindBaseLocalChanAlias(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerSignOutputRaw(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerComputeInputScript(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerSignMessage(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerVerifyMessage(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerDeriveSharedKey(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerMuSig2CombineKeys(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerMuSig2CreateSession(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerMuSig2RegisterNonces(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerMuSig2Sign(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerMuSig2CombineSig(char* data, int length, CCallback callback);
extern __declspec(dllexport) void signerMuSig2Cleanup(char* data, int length, CCallback callback);
extern __declspec(dllexport) void gossipSync(char* serviceUrl, char* cacheDir, char* dataDir, char* networkType, CCallback callback);
extern __declspec(dllexport) void cancelGossipSync(void);
extern __declspec(dllexport) void subscribeState(char* data, int length, CRecvStream rStream);
extern __declspec(dllexport) void getState(char* data, int length, CCallback callback);
extern __declspec(dllexport) void versionerGetVersion(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitListUnspent(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitLeaseOutput(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitReleaseOutput(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitListLeases(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitDeriveNextKey(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitDeriveKey(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitNextAddr(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitGetTransaction(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitListAccounts(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitRequiredReserve(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitListAddresses(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitSignMessageWithAddr(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitVerifyMessageWithAddr(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitImportAccount(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitImportPublicKey(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitImportTapscript(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitPublishTransaction(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitRemoveTransaction(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitSendOutputs(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitEstimateFee(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitPendingSweeps(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitBumpFee(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitBumpForceCloseFee(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitListSweeps(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitLabelTransaction(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitFundPsbt(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitSignPsbt(char* data, int length, CCallback callback);
extern __declspec(dllexport) void walletKitFinalizePsbt(char* data, int length, CCallback callback);
extern __declspec(dllexport) void genSeed(char* data, int length, CCallback callback);
extern __declspec(dllexport) void initWallet(char* data, int length, CCallback callback);
extern __declspec(dllexport) void unlockWallet(char* data, int length, CCallback callback);
extern __declspec(dllexport) void changePassword(char* data, int length, CCallback callback);
extern __declspec(dllexport) void watchtowerGetInfo(char* data, int length, CCallback callback);
extern __declspec(dllexport) void watchtowerClientAddTower(char* data, int length, CCallback callback);
extern __declspec(dllexport) void watchtowerClientRemoveTower(char* data, int length, CCallback callback);
extern __declspec(dllexport) void watchtowerClientDeactivateTower(char* data, int length, CCallback callback);
extern __declspec(dllexport) void watchtowerClientTerminateSession(char* data, int length, CCallback callback);
extern __declspec(dllexport) void watchtowerClientListTowers(char* data, int length, CCallback callback);
extern __declspec(dllexport) void watchtowerClientGetTowerInfo(char* data, int length, CCallback callback);
extern __declspec(dllexport) void watchtowerClientStats(char* data, int length, CCallback callback);
extern __declspec(dllexport) void watchtowerClientPolicy(char* data, int length, CCallback callback);

#ifdef __cplusplus
}
#endif
