"use strict";

// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file peersrpc/peers.proto (package peersrpc, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lightning } from "../lightning_pb.js";
/**
 * Describes the file peersrpc/peers.proto.
 */
export const file_peersrpc_peers = /*@__PURE__*/
fileDesc("ChRwZWVyc3JwYy9wZWVycy5wcm90bxIIcGVlcnNycGMiTgoTVXBkYXRlQWRkcmVzc0FjdGlvbhImCgZhY3Rpb24YASABKA4yFi5wZWVyc3JwYy5VcGRhdGVBY3Rpb24SDwoHYWRkcmVzcxgCIAEoCSJlChNVcGRhdGVGZWF0dXJlQWN0aW9uEiYKBmFjdGlvbhgBIAEoDjIWLnBlZXJzcnBjLlVwZGF0ZUFjdGlvbhImCgtmZWF0dXJlX2JpdBgCIAEoDjIRLmxucnBjLkZlYXR1cmVCaXQirQEKHU5vZGVBbm5vdW5jZW1lbnRVcGRhdGVSZXF1ZXN0EjYKD2ZlYXR1cmVfdXBkYXRlcxgBIAMoCzIdLnBlZXJzcnBjLlVwZGF0ZUZlYXR1cmVBY3Rpb24SDQoFY29sb3IYAiABKAkSDQoFYWxpYXMYAyABKAkSNgoPYWRkcmVzc191cGRhdGVzGAQgAygLMh0ucGVlcnNycGMuVXBkYXRlQWRkcmVzc0FjdGlvbiI4Ch5Ob2RlQW5ub3VuY2VtZW50VXBkYXRlUmVzcG9uc2USFgoDb3BzGAEgAygLMgkubG5ycGMuT3AqIwoMVXBkYXRlQWN0aW9uEgcKA0FERBAAEgoKBlJFTU9WRRABKmkKCkZlYXR1cmVTZXQSDAoIU0VUX0lOSVQQABIVChFTRVRfTEVHQUNZX0dMT0JBTBABEhAKDFNFVF9OT0RFX0FOThACEg8KC1NFVF9JTlZPSUNFEAMSEwoPU0VUX0lOVk9JQ0VfQU1QEAQydAoFUGVlcnMSawoWVXBkYXRlTm9kZUFubm91bmNlbWVudBInLnBlZXJzcnBjLk5vZGVBbm5vdW5jZW1lbnRVcGRhdGVSZXF1ZXN0GigucGVlcnNycGMuTm9kZUFubm91bmNlbWVudFVwZGF0ZVJlc3BvbnNlQjBaLmdpdGh1Yi5jb20vbGlnaHRuaW5nbmV0d29yay9sbmQvbG5ycGMvcGVlcnNycGNiBnByb3RvMw", [file_lightning]);

/**
 * @generated from message peersrpc.UpdateAddressAction
 */

/**
 * Describes the message peersrpc.UpdateAddressAction.
 * Use `create(UpdateAddressActionSchema)` to create a new message.
 */
export const UpdateAddressActionSchema = /*@__PURE__*/
messageDesc(file_peersrpc_peers, 0);

/**
 * @generated from message peersrpc.UpdateFeatureAction
 */

/**
 * Describes the message peersrpc.UpdateFeatureAction.
 * Use `create(UpdateFeatureActionSchema)` to create a new message.
 */
export const UpdateFeatureActionSchema = /*@__PURE__*/
messageDesc(file_peersrpc_peers, 1);

/**
 * @generated from message peersrpc.NodeAnnouncementUpdateRequest
 */

/**
 * Describes the message peersrpc.NodeAnnouncementUpdateRequest.
 * Use `create(NodeAnnouncementUpdateRequestSchema)` to create a new message.
 */
export const NodeAnnouncementUpdateRequestSchema = /*@__PURE__*/
messageDesc(file_peersrpc_peers, 2);

/**
 * @generated from message peersrpc.NodeAnnouncementUpdateResponse
 */

/**
 * Describes the message peersrpc.NodeAnnouncementUpdateResponse.
 * Use `create(NodeAnnouncementUpdateResponseSchema)` to create a new message.
 */
export const NodeAnnouncementUpdateResponseSchema = /*@__PURE__*/
messageDesc(file_peersrpc_peers, 3);

/**
 * UpdateAction is used to determine the kind of action we are referring to.
 *
 * @generated from enum peersrpc.UpdateAction
 */
export let UpdateAction = /*#__PURE__*/function (UpdateAction) {
  /**
   * ADD indicates this is an "insertion" kind of action.
   *
   * @generated from enum value: ADD = 0;
   */
  UpdateAction[UpdateAction["ADD"] = 0] = "ADD";
  /**
   * REMOVE indicates this is a "deletion" kind of action.
   *
   * @generated from enum value: REMOVE = 1;
   */
  UpdateAction[UpdateAction["REMOVE"] = 1] = "REMOVE";
  return UpdateAction;
}({});

/**
 * Describes the enum peersrpc.UpdateAction.
 */
export const UpdateActionSchema = /*@__PURE__*/
enumDesc(file_peersrpc_peers, 0);

/**
 * @generated from enum peersrpc.FeatureSet
 */
export let FeatureSet = /*#__PURE__*/function (FeatureSet) {
  /**
   * 
   * SET_INIT identifies features that should be sent in an Init message to
   * a remote peer.
   *
   * @generated from enum value: SET_INIT = 0;
   */
  FeatureSet[FeatureSet["SET_INIT"] = 0] = "SET_INIT";
  /**
   * 
   * SET_LEGACY_GLOBAL identifies features that should be set in the legacy
   * GlobalFeatures field of an Init message, which maintains backwards
   * compatibility with nodes that haven't implemented flat features.
   *
   * @generated from enum value: SET_LEGACY_GLOBAL = 1;
   */
  FeatureSet[FeatureSet["SET_LEGACY_GLOBAL"] = 1] = "SET_LEGACY_GLOBAL";
  /**
   * 
   * SET_NODE_ANN identifies features that should be advertised on node
   * announcements.
   *
   * @generated from enum value: SET_NODE_ANN = 2;
   */
  FeatureSet[FeatureSet["SET_NODE_ANN"] = 2] = "SET_NODE_ANN";
  /**
   * 
   * SET_INVOICE identifies features that should be advertised on invoices
   * generated by the daemon.
   *
   * @generated from enum value: SET_INVOICE = 3;
   */
  FeatureSet[FeatureSet["SET_INVOICE"] = 3] = "SET_INVOICE";
  /**
   * 
   * SET_INVOICE_AMP identifies the features that should be advertised on
   * AMP invoices generated by the daemon.
   *
   * @generated from enum value: SET_INVOICE_AMP = 4;
   */
  FeatureSet[FeatureSet["SET_INVOICE_AMP"] = 4] = "SET_INVOICE_AMP";
  return FeatureSet;
}({});

/**
 * Describes the enum peersrpc.FeatureSet.
 */
export const FeatureSetSchema = /*@__PURE__*/
enumDesc(file_peersrpc_peers, 1);

/**
 * Peers is a service that can be used to get information and interact
 * with the other nodes of the network.
 *
 * @generated from service peersrpc.Peers
 */
export const Peers = /*@__PURE__*/
serviceDesc(file_peersrpc_peers, 0);
//# sourceMappingURL=peers_pb.js.map