"use strict";

// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file stateservice.proto (package lnrpc, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
/**
 * Describes the file stateservice.proto.
 */
export const file_stateservice = /*@__PURE__*/
fileDesc("ChJzdGF0ZXNlcnZpY2UucHJvdG8SBWxucnBjIhcKFVN1YnNjcmliZVN0YXRlUmVxdWVzdCI7ChZTdWJzY3JpYmVTdGF0ZVJlc3BvbnNlEiEKBXN0YXRlGAEgASgOMhIubG5ycGMuV2FsbGV0U3RhdGUiEQoPR2V0U3RhdGVSZXF1ZXN0IjUKEEdldFN0YXRlUmVzcG9uc2USIQoFc3RhdGUYASABKA4yEi5sbnJwYy5XYWxsZXRTdGF0ZSpzCgtXYWxsZXRTdGF0ZRIQCgxOT05fRVhJU1RJTkcQABIKCgZMT0NLRUQQARIMCghVTkxPQ0tFRBACEg4KClJQQ19BQ1RJVkUQAxIRCg1TRVJWRVJfQUNUSVZFEAQSFQoQV0FJVElOR19UT19TVEFSVBD/ATKVAQoFU3RhdGUSTwoOU3Vic2NyaWJlU3RhdGUSHC5sbnJwYy5TdWJzY3JpYmVTdGF0ZVJlcXVlc3QaHS5sbnJwYy5TdWJzY3JpYmVTdGF0ZVJlc3BvbnNlMAESOwoIR2V0U3RhdGUSFi5sbnJwYy5HZXRTdGF0ZVJlcXVlc3QaFy5sbnJwYy5HZXRTdGF0ZVJlc3BvbnNlQidaJWdpdGh1Yi5jb20vbGlnaHRuaW5nbmV0d29yay9sbmQvbG5ycGNiBnByb3RvMw");

/**
 * @generated from message lnrpc.SubscribeStateRequest
 */

/**
 * Describes the message lnrpc.SubscribeStateRequest.
 * Use `create(SubscribeStateRequestSchema)` to create a new message.
 */
export const SubscribeStateRequestSchema = /*@__PURE__*/
messageDesc(file_stateservice, 0);

/**
 * @generated from message lnrpc.SubscribeStateResponse
 */

/**
 * Describes the message lnrpc.SubscribeStateResponse.
 * Use `create(SubscribeStateResponseSchema)` to create a new message.
 */
export const SubscribeStateResponseSchema = /*@__PURE__*/
messageDesc(file_stateservice, 1);

/**
 * @generated from message lnrpc.GetStateRequest
 */

/**
 * Describes the message lnrpc.GetStateRequest.
 * Use `create(GetStateRequestSchema)` to create a new message.
 */
export const GetStateRequestSchema = /*@__PURE__*/
messageDesc(file_stateservice, 2);

/**
 * @generated from message lnrpc.GetStateResponse
 */

/**
 * Describes the message lnrpc.GetStateResponse.
 * Use `create(GetStateResponseSchema)` to create a new message.
 */
export const GetStateResponseSchema = /*@__PURE__*/
messageDesc(file_stateservice, 3);

/**
 * @generated from enum lnrpc.WalletState
 */
export let WalletState = /*#__PURE__*/function (WalletState) {
  /**
   * NON_EXISTING means that the wallet has not yet been initialized.
   *
   * @generated from enum value: NON_EXISTING = 0;
   */
  WalletState[WalletState["NON_EXISTING"] = 0] = "NON_EXISTING";
  /**
   * LOCKED means that the wallet is locked and requires a password to unlock.
   *
   * @generated from enum value: LOCKED = 1;
   */
  WalletState[WalletState["LOCKED"] = 1] = "LOCKED";
  /**
   * UNLOCKED means that the wallet was unlocked successfully, but RPC server
   * isn't ready.
   *
   * @generated from enum value: UNLOCKED = 2;
   */
  WalletState[WalletState["UNLOCKED"] = 2] = "UNLOCKED";
  /**
   * RPC_ACTIVE means that the lnd server is active but not fully ready for
   * calls.
   *
   * @generated from enum value: RPC_ACTIVE = 3;
   */
  WalletState[WalletState["RPC_ACTIVE"] = 3] = "RPC_ACTIVE";
  /**
   * SERVER_ACTIVE means that the lnd server is ready to accept calls.
   *
   * @generated from enum value: SERVER_ACTIVE = 4;
   */
  WalletState[WalletState["SERVER_ACTIVE"] = 4] = "SERVER_ACTIVE";
  /**
   * WAITING_TO_START means that node is waiting to become the leader in a
   * cluster and is not started yet.
   *
   * @generated from enum value: WAITING_TO_START = 255;
   */
  WalletState[WalletState["WAITING_TO_START"] = 255] = "WAITING_TO_START";
  return WalletState;
}({});

/**
 * Describes the enum lnrpc.WalletState.
 */
export const WalletStateSchema = /*@__PURE__*/
enumDesc(file_stateservice, 0);

/**
 * State service is a always running service that exposes the current state of
 * the wallet and RPC server.
 *
 * @generated from service lnrpc.State
 */
export const State = /*@__PURE__*/
serviceDesc(file_stateservice, 0);
//# sourceMappingURL=stateservice_pb.js.map